name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid. Output the animation as gif or svg"
author: "platane"

outputs:
  gif_out_path:
    description: "path of the generated gif. If left empty, will not generate a gif file"
  svg_out_path:
    description: "path of the generated svg. If left empty, will not generate a svg file"

runs:
  using: "docker"
  image: "docker://platane/snk:latest"

inputs:
  github_user_name:
    description: "github user name"
    required: true
  gif_out_path:
    description: "path of the generated gif"
    required: false
    default: null
  svg_out_path:
    description: "path of the generated svg"
    required: false
    default: null
